defaults: &defaults
  parallelism: 2
  steps:
    - checkout
    - run: sudo apt-get install cmake
    - run: gem update --system
    - run: bundle install
    - run: bundle exec rubocop -D

version: 2
jobs:
  ruby_2_4:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4
  ruby_2_5:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4
  ruby_2_6:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4
workflows:
  version: 2
  test:
    jobs:
      - ruby_2_3
      - ruby_2_4
